name: Build_env

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build_env 
      run:  ./Build_Env.sh
    - name: build_subscriber
      run:  cd 3_Implementation/src/Subscriber && make
    - name: build_client
      run:  cd 3_Implementation/src/Clients && make 
    
